Automate releases
yamafaktory/jql pull request #141
Opened 2022-04-02 20:41 UTC by kmaasrud

Re.: #140 

Publishes a release on pushed version tags and builds binaries for that release. The workflow uses [rust-build.action](https://github.com/rust-build/rust-build.action), which means the supported triples are:

- `x86_64-pc-windows-gnu`
- `x86_64-unknown-linux-musl`
- `x86_64-apple-darwin`

Optimally, `aarch64-*` should be supported as well, but this has proven hard to cross-compile (after a lot of trial and error.) Either way, building for `x86` is a step in the right direction, and hopefully rust-build.action will support more triples in the future.

2022-04-02 21:20 UTC, yamafaktory requested changes
Thanks a ton @kmaasrud for your contribution!

I left some minor comments, please have a look 🙇‍♂️.

2022-04-02 21:20 UTC, yamafaktory commented on .github/workflows/build-release.yml
> +      - uses: actions/checkout@master
We need to use the `main` branch here:
```suggestion
      - uses: actions/checkout@v3
        with:
          ref: "main"
```

2022-04-02 21:20 UTC, yamafaktory commented on .github/workflows/release.yml
> +        uses: actions/checkout@v2
Here we can also use the latest `v3` (I'll need to bump up that too in the other `yaml` files):
```suggestion
        uses: actions/checkout@v3
```

2022-04-02 21:27 UTC, kmaasrud commented
Should be all good now! Happy I can contribute 😄

2022-04-02 21:33 UTC, yamafaktory commented on .github/workflows/build-release.yml
> +          ref: "main"
Actually, this might not even be needed based on the documentation (https://github.com/actions/checkout):
> Otherwise, uses the default branch.

2022-04-02 21:38 UTC, yamafaktory approved these changes
🎉

2022-04-02 22:22 UTC, yamafaktory commented
Thanks for the contribution @kmaasrud ! I'll create a new release tomorrow.

2022-04-02 22:22 UTC, merged

2022-04-03 20:37 UTC, yamafaktory commented
An update on this: sadly it doesn't work as expected due to https://github.community/t/workflow-set-for-on-release-not-triggering-not-showing-up/16286/3. The event is never triggered, hence no binaries (I tried to force-run the action manually for testing reasons but it fails because it needs the event).

2022-04-03 20:44 UTC, yamafaktory commented
I guess one solution might be to move the `build-release`job into the the `release.yml` action and make it triggered by the `publish-release` job (so no `on:` -> `release:` -> `types: [created]`).

2022-04-04 07:32 UTC, kmaasrud commented
rust-build.action only works on a release, since it does not create a release itself, but only publishes the assets to it. I added a job on `release.yml` that simply creates an empty release on newly pushed version tags, which subsequently should trigger the `on: release: types: [created] `.

Have you tried manually creating a release for the newest tag to see if the workflow is triggered by that? Whenever a new tag is pushed, a release should be created automatically, if I have tested everything correctly.

2022-04-04 07:35 UTC, kmaasrud commented
If the event is not triggered by releases as hoped, we might have to do everything on the tag event, which would mean writing a manual workflow instead of relying on rust-build.action.

Keep me posted on if the things I wrote above works or not. If it doesn't, I'll do a new PR with a build workflow written from scratch :+1:

2022-04-04 07:41 UTC, yamafaktory commented
@kmaasrud that's the problem, see https://github.community/t/workflow-set-for-on-release-not-triggering-not-showing-up/16286/5.  I haven't tested a manual tag but I'm pretty confident it will work. Our issue is that a workflow can't be triggered by another one. rust-build.action is presumably working out of the box if you use the web interface (which we don't want). If we combine both workflows and make rust-build.action dependent on the release it might also work https://docs.github.com/en/actions/using-workflows/advanced-workflow-features#creating-dependent-jobs.

2022-04-04 07:44 UTC, kmaasrud commented
Ah of course! That would probably work, yes; I'll make a PR for it at once

2022-04-04 07:59 UTC, yamafaktory commented
@kmaasrud  thanks for the feedback. I was fearing that it was indeed relying on the event directly...